run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
  disable-all: true

issues:
  exclude-use-default: false
