ALTER TABLE urls ADD COLUMN max_accesses INT NULL;
ALTER TABLE urls ADD COLUMN access_count INT NOT NULL DEFAULT 0;
ALTER TABLE urls ADD COLUMN password_hash TEXT NULL;
ALTER TABLE urls ADD COLUMN is_enabled BOOLEAN NOT NULL DEFAULT true;
